### ISSUE TITLE
Shoemacker, Cutter, juweler magician

### ISSUE THREAD

**Issue by joiyco** [F-Locos/StarLoco---Game#3]
Hello Just Want to Sax thank you First for the great Work. I Just have an issue with the magicians of shoemaker,Cutter,juweler. I can't Visit the maps of bonta and brakmar magicians craft House, is that an issue on my maps or do I have to add it anywhere? 

Thank you for any help.

**Comment by 1150706** [comment]
go into your scripted_cells table, in your starloco_game database and add the following line:
![image](https://user-images.githubusercontent.com/45335934/51067444-42571c80-160a-11e9-9c8c-e71a0e21911e.png)
this is just for the bonta mageshop, the brakmar one , you just need to change the mapid and cellid and the actions args

**Comment by F-Locos** [comment]
You should use the admin command instead
