### ISSUE TITLE
Error map not loading

### ISSUE THREAD

**Issue by 4ccr0z** [F-Locos/StarLoco---Game#6]
When i move on a map (dunjeon map for exemple) i have a error message in a client Dofus. Impossible de charger la carte => impossible loading map

**Comment by F-Locos** [comment]
Your lang are not configured, check your config.xml
The database use the 1.23 maps data, it's mandatory to found the good folder or change your maps table.

**Comment by Catvert** [comment]
Hey, j'ai la même erreur que @4ccr0z, que veux-tu dire par ta langue n'est pas configuré ? Je ne vois rien en rapport avec ça dans le fichier config.xml. Doit-on télécharger les maps de la 1.23?
