### ISSUE TITLE
Librairies

### ISSUE THREAD

**Issue by Docteur-Strange** [F-Locos/StarLoco---Game#7]
Salut !
Tout d'abord, un grand merci et bravo pour ce boulot énorme.

J'aimerais te demander si tu peux nous communiquer les libraires que tu as utilisées ?
Car j'ai beaucoup de mal à compiler les sources, énormément d'erreurs, sûrement dues aux libraires inexistantes ?

Merci à toi !

**Comment by F-Locos** [comment]
Salut,

Le projet est sous maven, le téléchargement des librairies se fait automatiquement.
Tu peux retrouvé la liste des librairies utilisées dans le fichier `pom.xml` à la racine du projet.

**Comment by Docteur-Strange** [comment]
Réponse précise, écrasante et ultime dans ma jugulaire.
Merci à toi, homme de l'ombre.
