### ISSUE TITLE
GameHandler.java et erreur console

### ISSUE THREAD

**Issue by Docteur-Strange** [F-Locos/StarLoco---Game#8]
Salut, je reviens vers toi pour d'autres soucis.

Mon premier soucis concerne le "log" dans GameHandler.java.

![log error](https://user-images.githubusercontent.com/42722524/58514493-6aeb4780-81a2-11e9-8be3-5f03fc500ef0.png)

Mon second est plus casse-tête, c'est quand j'essaie de run le Main du projet Game.

![error no source](https://user-images.githubusercontent.com/42722524/58510853-e268a900-8199-11e9-9a3d-fa57d532b7ef.png)

J'ai cherché à comprendre de quels fichiers sources il s'agit, sûrement ceux de Kotlin ? path de mon Java ? J'ai malheureusement pas réussi à réparer cette erreur.

Bien à toi !

**Comment by F-Locos** [comment]
Re,

Tu peux stocké l'instance GameClient dans une variable et faire :
`client.logger.info(...);`

**Comment by Docteur-Strange** [comment]
Pour le second problème tu ne sais pas d'où cela proviendrait ?

**Comment by Docteur-Strange** [comment]
![getgroupe](https://user-images.githubusercontent.com/42722524/58677155-2c4cbd00-835b-11e9-81f3-79e2a3db991b.png)

`/src/main/java/org/starloco/locos/common/ConditionParser.java:[95,53] incompatible types: boolean cannot be converted to double`

Il y a un soucis avec celui là, c'est l'une des dernières erreurs que j'ai pour la compilation.

**Comment by Docteur-Strange** [comment]
Problème réglé !

J'ai dû mettre à jour les "dependencies" dans le pom.xl car ma version de java (JDK11) n'acceptait pas les anciennes versions.
