### ISSUE TITLE
Abonnement

### ISSUE THREAD

**Issue by Docteur-Strange** [F-Locos/StarLoco---Game#9]
Re,

Après avoir activé le système d'abonnement :
`options.subscription = true`

EDIT (02/06/2019) : J'ai réussi à m'ajouter en jeu 86400000 en colonne Subscribe, ce qui équivaut à 1 jour si je ne me trompe pas. Mais à chaque fois que je change de perso ou déco/reco, ça disparaît, j'ai pourtant checké un peut partout pour voir si la variable retombe à 0 ou est rechargé. Je suis un peu perdu.

Il me faudrait comprendre comment faire pour que la colonne Subscribe reste inchangée à chaque déco/reco/changement de perso. Si tu pouvais m'aiguiller.

**Comment by Docteur-Strange** [comment]
J'ai réussi à m'ajouter en jeu 86400000 en colonne Subscribe, ce qui équivaut à 1 jour si je ne me trompe pas. Mais à chaque fois que je change de perso ou déco/reco, ça disparaît, j'ai pourtant checké un peut partout pour voir si la variable retombe à 0 ou est rechargé. Je suis un peu perdu.

**Comment by Docteur-Strange** [comment]
Bon, j'ai réussi à le faire après de nombreux tests.

**Comment by F-Locos** [comment]
> Bon, j'ai réussi à le faire après de nombreux tests.

Il est toujours intéressant de poster la solution, ça serait peut être utile pour les autres.
ça doit être :
end = System.currentTimeMillis() + le temps d'abo en millisecondes
Et dans l'émulateur ça compare :
si System.currentTimeMillis() > end alors il n'est plus abonné et on remet ça valeur à 0.

**Comment by Docteur-Strange** [comment]
En effet, je m'excuse.

> CommandPlayer.java
`else if (command(msg, "subsevendays")) {
                    // Ajoutez ici plusieurs conditions avant d'appeler la méthode
                    player.getAccount().addSubscribe(604800000);
                    player.sendMessage("7 jours d'abonnement ajouté(s).");
                    return true;
 }`
Cette commande ajoute spécifiquement 7 jours d'abonnement.
*player.getAccount().addSubscribe(604800000)* -> 604800000 étant des millisecondes, équivalent à 7 jours. 
Je vous laisse rajouter vos conditions, si vous voulez faire un système de points, une potion pour invoquer la commande, etc. Libre à vous.

> Account.java
`public void addSubscribe(long l) {
        this.subscribe += l ;
        Database.getStatics().getAccountData().updateSubscribe(id, this.subscribe);
    }`
Cette commande permet à l'abonnement de s'accumuler et de faire appel à la méthode de mise à jour.

> AccountData.java
`/** Abonnement **/

    public long getSubscribe(int account) {
        Result result = null;
        long subscribe = 0;
        try {
            result = super.getData("SELECT guid, subscribe FROM accounts WHERE guid = " + account);

            if(result != null) {
                ResultSet RS = result.resultSet;
                while (RS.next()) {
                    subscribe = RS.getLong("subscribe");
                }
            }
        } catch (Exception e) {
            super.sendError("AccountData load id", e);
        } finally {
            close(result);
        }
        return subscribe;
    }

    public long loadSubscribe(String user) {
        return Database.getStatics().getAccountData().loadSubscribeWithoutUsersDb(user);
    }

    public long loadSubscribeWithoutUsersDb(String user) {
        Result result = null;
        long subscribe = 0;
        try {
            result = super.getData("SELECT * from accounts WHERE `account` LIKE '"
                    + user + "'");
            ResultSet RS = result.resultSet;
            if (RS.next()) {
                subscribe = RS.getLong("subscribe");
            }
        } catch (SQLException e) {
            super.sendError("AccountData loadSubscribe", e);
        } finally {
            close(result);
        }
        return subscribe;
    }

    public void updateSubscribe(int id, long subscribe) {
        Database.getStatics().getAccountData().updateSubscribeWithoutUsersDb(id, subscribe);
    }

    public void updateSubscribeWithoutUsersDb(int id, long subscribe) {
        PreparedStatement p = null;
        try {
            p = getPreparedStatement("UPDATE accounts SET `subscribe` = ? WHERE `guid` = ?");
            p.setLong(1, subscribe);
            p.setInt(2, id);
            execute(p);
        } catch (SQLException e) {
            super.sendError("AccountData updateSubscribe", e);
        } finally {
            close(p);
        }
    }
`
Tout ce code comprend donc la mise à jour et le chargement de "subscribe" de la BDD (dans Accounts).
Il y avait déjà un bout de code au préalable fait pour les points dans cette section. J'ai juste recopié le code et l'ai adapté pour l'abonnement.

En espérant que cela aide.

Si tu veux un truc qui cloche Locos n'hésite pas.

Bien à vous !

**Comment by Docteur-Strange** [comment]
En passant Locos, il serait possible de te contacter ? Discord, mail, etc.
